apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/etc/kubernetes/scheduler.conf"
profiles:
- schedulerName: default-scheduler
  plugins:
    preFilter:
      enabled:
      - name: OptimizedPreemption
        weight: 100
    filter:
      enabled:
      - name: OptimizedPreemption
        weight: 100
    postFilter:
      enabled:
      - name: OptimizedPreemption
        weight: 0
  pluginConfig:
  - name: OptimizedPreemption
    args:
      timeout: 120000
