apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-a-deployment
  labels:
    app: pod-a
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: pod-a
  template:
    metadata:
      labels:
        pod: pod-a
    spec:
      containers:
      - name: stress-box
        image: alpine:latest
        resources:
          requests:
            cpu: "1000m"
            memory: "2490Mi"
          limits:
            cpu: "1000m"
            memory: "2490Mi"
