apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-b-bis-deployment
  labels:
    app: pod-b-bis
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: pod-b-bis
  template:
    metadata:
      labels:
        pod: pod-b-bis
    spec:
      containers:
      - name: stress-box
        image: alpine:latest
        resources:
          requests:
            cpu: "1000m"
            memory: "2120Mi"
          limits:
            cpu: "1000m"
            memory: "2120Mi"
