apiVersion: v1
kind: Pod
metadata:
  name: pod-stress
spec:
  containers:
  - name: stress-box
    image: alpine:latest
    #    volumeMounts:
    #      - name: my-volume
    #        mountPath: /opt/my-volume
    resources:
      requests:
        cpu: "1000m"
        memory: "2220Mi"
      limits:
        cpu: "1000m"
        memory: "2220Mi"
    command: ["sh", "-c", "apk add --no-cache stress-ng && grep MemTotal /proc/meminfo && awk '/MemTotal/{print int($2*0.99)}' /proc/meminfo && stress-ng --vm 1 --vm-bytes $(awk '/MemTotal/{print int($2*0.99)}' /proc/meminfo)k --timeout 60s --vm-keep"]
    #  volumes:
    #    - name: my-volume
    #      configMap:
    #        name: my-script
