apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-b-deployment
  labels:
    app: pod-b
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: pod-b
  template:
    metadata:
      labels:
        pod: pod-b
    spec:
      containers:
        - name: stress-box
          image: alpine:latest
          stdin: true
          tty: true
          resources:
            requests:
              cpu: "1000m"
              memory: "1000Mi"
            limits:
              cpu: "1000m"
              memory: "1000Mi"
